
ARG BASE_IMAGE
ARG ROS_DISTRO
FROM ${BASE_IMAGE} as exp

SHELL [ "/bin/bash","-c" ]

###################################
# Turtlebot system
# Checked : 2024/12/29
###################################
# https://docs.nav2.org/getting_started/index.html#getting-started
RUN apt update && apt install \
  ros-$ROS_DISTRO-navigation2 \
  ros-$ROS_DISTRO-nav2-bringup \
  ros-$ROS_DISTRO-nav2-minimal-tb*
